maxUniverses: 2

fixtures:
  # Laser
  - id: 13
    name: "Laser RGB"
    type: "simple"
    model: "Laser"
    universe: 1
    address: 10
    manufacturer: "Generic"
    mode: "24 Channel"
    activo: true
    sceneIdOn: 10013
    sceneIdOff: 20013
  
  # Moving Head beam+spot
  - id: 8
    name: "beam+spot 1"
    type: "robotic"
    model: "beam+spot"
    universe: 1
    address: 40
    manufacturer: "china"
    mode: "Normal"
    activo: true
    sceneIdOn: 10008
    sceneIdOff: 20008
  
  - id: 10
    name: "beam+spot 2"
    type: "robotic"
    model: "beam+spot"
    universe: 1
    address: 55
    manufacturer: "china"
    mode: "Normal"
    activo: true
    sceneIdOn: 10010
    sceneIdOff: 20010
  
  - id: 11
    name: "beam+spot 3"
    type: "robotic"
    model: "beam+spot"
    universe: 1
    address: 70
    manufacturer: "china"
    mode: "Normal"
    activo: true
    sceneIdOn: 10011
    sceneIdOff: 20011
  
  - id: 18
    name: "beam+spot 4"
    type: "robotic"
    model: "beam+spot"
    universe: 1
    address: 90
    manufacturer: "china"
    mode: "Normal"
    activo: true
    sceneIdOn: 10018
    sceneIdOff: 20018
  
  # Derby
  - id: 7
    name: "Derby 1"
    type: "simple"
    model: "Derby"
    universe: 1
    address: 150
    manufacturer: "Wild Pro"
    mode: "Derby Normal"
    activo: true
    sceneIdOn: 10007
    sceneIdOff: 20007
  
  - id: 6
    name: "Derby 2"
    type: "simple"
    model: "Derby"
    universe: 1
    address: 181
    manufacturer: "Wild Pro"
    mode: "Derby Normal"
    activo: true
    sceneIdOn: 10006
    sceneIdOff: 20006
  
  # Moving Head 2
  - id: 9
    name: "Moving Head 3"
    type: "robotic"
    model: "Moving Head 2"
    universe: 1
    address: 240
    manufacturer: "generic"
    mode: "normal"
    activo: true
    sceneIdOn: 10009
    sceneIdOff: 20009
  
  - id: 12
    name: "Moving Head 4"
    type: "robotic"
    model: "Moving Head 2"
    universe: 1
    address: 260
    manufacturer: "generic"
    mode: "normal"
    activo: true
    sceneIdOn: 10012
    sceneIdOff: 20012
  
  # Spider
  - id: 4
    name: "Spider 2"
    type: "simple-robotic"
    model: "Spider"
    universe: 1
    address: 300
    manufacturer: "generic"
    mode: "spider"
    activo: true
    sceneIdOn: 10004
    sceneIdOff: 20004
  
  - id: 5
    name: "Spider 3"
    type: "simple-robotic"
    model: "Spider"
    universe: 1
    address: 320
    manufacturer: "generic"
    mode: "spider"
    activo: true
    sceneIdOn: 10005
    sceneIdOff: 20005
  
  # RGBW
  - id: 0
    name: "RGBW id1"
    type: "simple"
    model: "RGBW"
    universe: 1
    address: 400
    manufacturer: "Wild Pro"
    mode: "Normal"
    activo: true
    sceneIdOn: 10000
    sceneIdOff: 20000
  
  - id: 1
    name: "RGBW Id2"
    type: "simple"
    model: "RGBW"
    universe: 1
    address: 410
    manufacturer: "Wild Pro"
    mode: "Normal"
    activo: true
    sceneIdOn: 10001
    sceneIdOff: 20001
  
  - id: 2
    name: "RGBW id3"
    type: "simple"
    model: "RGBW"
    universe: 1
    address: 420
    manufacturer: "Wild Pro"
    mode: "Normal"
    activo: true
    sceneIdOn: 10002
    sceneIdOff: 20002
  
  - id: 3
    name: "RGBW id4"
    type: "simple"
    model: "RGBW"
    universe: 1
    address: 430
    manufacturer: "Wild Pro"
    mode: "Normal"
    activo: true
    sceneIdOn: 10003
    sceneIdOff: 20003
  
  # Moving Head Beam
  - id: 14
    name: "Moving Head Beam 1"
    type: "robotic"
    model: "Moving Head"
    universe: 1
    address: 440
    manufacturer: "MovingHead"
    mode: "normal"
    activo: true
    sceneIdOn: 10014
    sceneIdOff: 20014
  
  - id: 15
    name: "Moving Head Beam 2"
    type: "robotic"
    model: "Moving Head"
    universe: 1
    address: 452
    manufacturer: "MovingHead"
    mode: "normal"
    activo: true
    sceneIdOn: 10015
    sceneIdOff: 20015
  
  - id: 16
    name: "Moving Head Beam 3"
    type: "robotic"
    model: "Moving Head"
    universe: 1
    address: 464
    manufacturer: "MovingHead"
    mode: "normal"
    activo: true
    sceneIdOn: 10016
    sceneIdOff: 20016
  
  - id: 17
    name: "Moving Head Beam 4"
    type: "robotic"
    model: "Moving Head"
    universe: 1
    address: 476
    manufacturer: "MovingHead"
    mode: "normal"
    activo: true
    sceneIdOn: 10017
    sceneIdOff: 20017
  
  # Bee Eye (Universe 2)
  - id: 20
    name: "BeeEye 1"
    type: "robotic"
    model: "Moving Head Bee Eye"
    universe: 2
    address: 2
    manufacturer: "Wild Pro"
    mode: "Moving Head"
    activo: true
    sceneIdOn: 10020
    sceneIdOff: 20020
  
  - id: 21
    name: "BeeEye 2"
    type: "robotic"
    model: "Moving Head Bee Eye"
    universe: 2
    address: 50
    manufacturer: "Wild Pro"
    mode: "Moving Head"
    activo: true
    sceneIdOn: 10021
    sceneIdOff: 20021
  
  - id: 22
    name: "BeeEye 3"
    type: "robotic"
    model: "Moving Head Bee Eye"
    universe: 2
    address: 100
    manufacturer: "Wild Pro"
    mode: "Moving Head"
    activo: true
    sceneIdOn: 10022
    sceneIdOff: 20022
  
  - id: 23
    name: "BeeEye 4"
    type: "robotic"
    model: "Moving Head Bee Eye"
    universe: 2
    address: 150
    manufacturer: "Wild Pro"
    mode: "Moving Head"
    activo: true
    sceneIdOn: 10023
    sceneIdOff: 20023

